FROM python:3.12-slim

RUN groupadd --gid 1000 sod_user \
    && useradd --uid 1000 --gid 1000 -ms /bin/bash sod_user

RUN pip3 install --no-cache-dir --upgrade \
    pip \
    virtualenv

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git

COPY run.sh /home/sod_user
RUN chmod +x /home/sod_user/run.sh

USER sod_user
WORKDIR /home/sod_user

COPY client.py /home/sod_user/app/
COPY i18n /home/sod_user/app/i18n/
COPY requirements.txt /home/sod_user/app/

ENV VIRTUAL_ENV=/home/sod_user/venv
RUN virtualenv ${VIRTUAL_ENV}
RUN . ${VIRTUAL_ENV}/bin/activate && pip install -r app/requirements.txt

EXPOSE 8501

ENTRYPOINT ["./run.sh"]
